
export const TYPES = {
    RESET: 'RESET',
    UPDATE_STATUS: 'UPDATE-STATUS',
    COUNTING: 'COUNTING',
    UPDATE_HIGHESTSPEED: 'UPDATE-HIGHESTSPEED',
    FLIP: 'FLIP',
    FLIPS: 'FLIPS',
    DECREASE_MATCH: 'DECREASE-MATCH',
    DISPLAY_RANK: 'DISPLAY-RANK'
};
