
export const TYPES = {
    RESET: 'RESET',
    UPDATE_STATUS: 'UPDATE-STATUS',
    COUNTING: 'COUNTING',
    UPDATE_HIGHESTSPEED: 'UPDATE-HIGHESTSPEED',
    FLIP: 'FLIP',
    FLIPS: 'FLIPS',
    DECREASE_MATCH: 'DECREASE-MATCH',
    TOGGLE_RANK: 'TOGGLE-RANK',
    TOGGLE_NAMEINPUT: 'TOGGLE-NAMEINPUT',
    UPDATE_USERNAME: 'UPDATE-USERNAME'
};
